name: Build

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_SERVER_URL: ${{ secrets.TEST_SERVER_URL }}
      ACROLINX_API_TOKEN: ${{ secrets.ACROLINX_API_TOKEN }}
      ACROLINX_DEV_SIGNATURE: ${{ secrets.ACROLINX_DEV_SIGNATURE}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Build And Run Tests
        run: |
          npm ci
          npm run build
          npm run test
